### ISSUE TITLE
Use of hand data set

### ISSUE THREAD

**Issue by 61linger** [heqin-zhu/UOD_universal_oneshot_detection#1]
Hello, I have some questions about the hand data set you used. You mentioned in your paper that you used 909 images in the hand data set, but in the csv file you provided, I extracted the labels of 910 images. Is there any image that has been removed?

**Comment by heqin-zhu** [comment]
Yes. When processing the hand dataset, this sample will raise exception.

**Comment by 5k5000** [comment]
Hi @Heqin, Could you point out which sample you discarded, and may you provide the code for computing the physical distance of the hand datasets?

**Comment by heqin-zhu** [comment]
Hi @5k5000 ,@61linger! The disgarded sample is `3142`. The physical distance (mm) of the hand dataset can be calculated in this way:  `physical_dis =  pixel_dis * 50 / radial(gt_points[0], gt_points[4])`. I implemented this in [evaluate.py](https://github.com/heqin-zhu/UOD_universal_oneshot_detection/blob/master/UOD/evaluate.py) at line 317.
