### ISSUE TITLE
Question for Training Data

### ISSUE THREAD

**Issue by Oceandeepzxr** [heqin-zhu/UOD_universal_oneshot_detection#2]
Hi guys, nice work! I just downloaded your code but I didnt find how to organize data, could you provide an example of training data? Btw how to organize training data is also important to me. Thx :D

**Comment by heqin-zhu** [comment]
Hi there!

The data can be organized as [GU2Net](https://github.com/MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection) does.
